package com.skydoves.processor;

import android.content.Context;
import android.content.SharedPreferences;

import com.skydoves.kickback.factory.SharedPreferencesFactory;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterSpec;
import com.squareup.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;

/**
 * Created by skydoves on 2018. 5. 8.
 * Copyright (c) 2018 battleent All rights reserved.
 */

public class PreferencesFactoryImplGenerator {

    private final KickbackBoxAnnotatedClass annotatedClazz;

    private final String CLAZZ_POSTFIX = "PreferencesFactoryImpl";

    public PreferencesFactoryImplGenerator(KickbackBoxAnnotatedClass annotatedClazz) {
        this.annotatedClazz = annotatedClazz;
    }

    public TypeSpec generate() {
        MethodSpec createMethod = MethodSpec.methodBuilder("create")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ParameterSpec.builder(Context.class, "context", Modifier.FINAL).build())
                .addStatement("return context.getSharedPreferences($S, Context.MODE_PRIVATE)", annotatedClazz.boxName)
                .returns(SharedPreferences.class)
                .build();

        return TypeSpec.classBuilder(getClassName())
                .addJavadoc("Generated by Kickback. (https://github.com/skydoves/Kickback).\n")
                .addModifiers(Modifier.PUBLIC)
                .superclass(SharedPreferencesFactory.class)
                .addMethod(createMethod)
                .build();
    }

    private String getClassName() {
        return this.annotatedClazz.boxName + CLAZZ_POSTFIX;
    }
}
